version: "3.7"

volumes:
  pg_data: {}

services:
  db:
    image: postgres:16.3
    restart: always
    ports:
      - "5434:5432"
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data
